### ISSUE TITLE
`withdrawlog` shows 0 refund amount

### ISSUE THREAD

**Issue by YaroShkvorets** [pomelo-io/pomelo-bounties-contract#14]
https://bloks.io/transaction/c191a81d858c1a61192227681115879d786cd482a48c21e2cc32815511d82644?tab=traces

Should show the amount that was refunded to the author

**Comment by YaroShkvorets** [comment]
Fixed, deployed to d.w.pomelo

**Comment by DenisCarriere** [comment]
Confirmed, fixed 👍
