### ISSUE TITLE
Add logging inline actions

### ISSUE THREAD

**Issue by DenisCarriere** [pomelo-io/pomelo-bounties-contract#3]
- [x] `depositlog`
- [x] `createlog`
- [x] `bountylog` (any changes related to bounties state)
- [x] `claimlog`
- [x] ???
- [ ] ???

## Example

https://github.com/eosnetworkfoundation/eosio.yield-contracts/blob/main/contracts/eosio.yield/src/logs.cpp

**Comment by YaroShkvorets** [comment]
Done.
Added 5 actions:

- depositlog
- createlog
- statelog
- claimlog
- withdrawlog

**Comment by DenisCarriere** [comment]
Implemented
